### ISSUE TITLE
Apprise multi-messenger plugin support for APRS

### ISSUE THREAD

**Issue by joergschultzelutter** [aprsorg/aprs-deviceid#100]
Hello Hessu,

I am in the process of finalizing my work on an multi-messenger plugin for APRS. The [multi-messenger in question](https://github.com/caronc/apprise) allows users to send content to  messenger clients such as Telegram, MS Teams etc through the initiation of a single program call. My plugin will enable authorized ham radio users to send messages to 1..n APRS call signs. 

For illustration purposes: The plugin in question is an amended version of my [DAPNET messenger plugin](https://github.com/caronc/apprise/wiki/Notify_dapnet) for Apprise which allows ham radio users to send messages to the [DAPNET pager network](https://hampager.de/#/). My new plugin will send a single up-to-67-chars APRS message to 1..n call signs and has already been successfully tested.

* [Original "Apprise" repository](https://github.com/caronc/apprise)
* [Forked work version](https://github.com/joergschultzelutter/apprise)

My work's focus solely lies [on the single APRS plugin](https://github.com/joergschultzelutter/apprise/blob/master/apprise/plugins/NotifyAprs.py) and **NOT** on the whole Apprise software package. I am aware of the regulation where one should not request a TOCALL on another person's behalf - however, the author of the multi-messenger software is not a licensed ham radio amateur and therefore cannot state this request. Therefore, I suggest using my contact details on the author's behalf.

Basic summary:

`tocall` : your choice
`(Plugin) vendor`: Joerg, DF1JSL
`(Software) vendor`: Chris, https://github.com/caronc
`model`: Apprise
`contact`: joerg.schultze.lutter@gmail.com
`OS`: Multiple
`Class`: service 
`Features`: messaging

Additionally, please consider [updating my existing APRS bot's](https://github.com/joergschultzelutter/mpad) TOCALL information - initially assigned by the late Bob Bruninga:

Current setting:

`
      "APMPAD" : {
         "vendor" : "DF1JSL",
         "model" : "WXBot clone and extension"
`

The bot has grown way past of its original scope, meaning that I no longer consider it as a mere clone. My suggested update:

`tocall`: APMPAD
`Vendor`: Joerg, DF1JSL
`contact`: joerg.schultze.lutter@gmail.com
`model`: Multi-Purpose APRS Daemon
`OS`: Multiple
`Class`: service
`Features`: messaging

Thank you!

73 de Joerg/DF1JSL

**Comment by hessu** [comment]
Hi,

Since the request is for the plugin, I'll register as follows:

```
 - tocall: APPRIS
   vendor: DF1JSL
   model: Apprise APRS plugin
   class: service
   contact: joerg.schultze.lutter@gmail.com
   features:
     - messaging
```

I hope that's OK. Also updating the APMPAD entry. I've dropped the OS: Multiple as such entries are not present in other allocations; I believe it's not necessary to specify OS if it's multiplatform. Let me know if there are further changes or improvements needed.
