### ISSUE TITLE
Add Open-Source SMS Gateway

### ISSUE THREAD

**Issue by na7q** [aprsorg/aprs-deviceid#102]
I would like to get my SMS Gateway added to the ToCall list if possible.

tocall: APOSMS
vendor: Mike, NA7Q
model: Open Source SMS Gateway
class: Service
os: Multiple
contact: mike.ph4@gmail.com
features: Messaging

[https://github.com/na7q/SMSGateway](url)
Mike, NA7Q

**Comment by hessu** [comment]
Thanks,

Allocated as requested.
