### ISSUE TITLE
New APRS TOCALL Request: JuFo Balloon Project

### ISSUE THREAD

**Issue by DL9AS** [aprsorg/aprs-deviceid#104]
Hello Hessu,

I was asked to add a unique APRS tocall to aid detection and telemetry extraction for the JuFo balloon project. https://github.com/DL9AS/jufo-project-radiosonde/issues/5 

I would therefore like to kindly ask if it is possible to allocate the following record:
```
 - tocall: APMON?
   vendor: Amon Schumann, DL9AS
   model: APRS Balloon Tracker
   class: tracker
   os: embedded
```

Thank you in advance and kind regards,

Amon

**Comment by hessu** [comment]
Thanks for the request, allocated as requested.

That said, I think packet contents should be parsed based on the contents, not based on which software sent them, as other software might choose to use the same format later on.
