### ISSUE TITLE
New APRS TOCALL Request: Yaesu FTM-200D

### ISSUE THREAD

**Issue by gsm-com** [aprsorg/aprs-deviceid#105]
mice:
 - suffix: "_2"
   vendor: Yaesu
   model: FTM-200
   class: rig

- tocall: APY200
   vendor: Yaesu
   model: FTM-200
   class: rig

**Comment by hessu** [comment]
Hi,

I'm sorry, but I'm waiting for Yaesu to establish communications on their allocations.
