### ISSUE TITLE
DO1MA FemtoAPRS Device ID: APFMT?

### ISSUE THREAD

**Issue by MarvinRzok** [aprsorg/aprs-deviceid#107]
Hello,
I am building a new LoRa-APRS Tracker, and i want to "Register" it here.

tocall: APFMT?
vendor: DO1MA
model: FemtoAPRS
class: tracker
os: embedded 

You can find Information here: https://github.com/MarvinRzok/FemtoAPRS-V1

APFMT? means that i can use any number or letter as a symbol for "?" so i can identify the different versions, right?

Best regards Marvin

**Comment by hessu** [comment]
Hi,

How about allocating APLFM? for this, as other LoRa trackers have recently been allocated in the APL*  prefix?

Yes, a wildcard character can be allocated in the end like that.

**Comment by MarvinRzok** [comment]
Hello,
Yes, APLFM? will work fine. 
Please add it to the Database.
Best regards Marvin

**Comment by hessu** [comment]
Hi!

Sorry for the delay. Allocated APLFM? for you now.
