### ISSUE TITLE
Tocall Satellite Gateway

### ISSUE THREAD

**Issue by na7q** [aprsorg/aprs-deviceid#108]
tocall: APOSAT
vendor: Mike, NA7Q
model: Open Source Satellite Gateway
class: Service
os: Multiple
contact: [mike.ph4@gmail.com](mailto:mike.ph4@gmail.com)
features: Position Reporting via SMS Satellite Messaging

[https://github.com/na7q/Sat2APRS](https://github.com/aprsorg/aprs-deviceid/issues/url)
Mike, NA7Q

**Comment by na7q** [comment]
https://aprs.fi/info/a/SATGTE

**Comment by hessu** [comment]
Hi,

Allocating as follows, the features field is not free text:

```
 - tocall: APOSAT
   vendor: Mike, NA7Q
   model: Open Source Satellite Gateway
   class: service
   contact: mike.ph4@gmail.com
```
