### ISSUE TITLE
TOCALL Request: APRS-Tempest / KL7AF

### ISSUE THREAD

**Issue by snopro** [aprsorg/aprs-deviceid#109]
tocall: APTEMP
vendor: KL7AF
model: APRS-Tempest Weather Gateway
class: wx
os: Linux/Unix
contact: [kl7af@foghaven.net](mailto:kl7af@foghaven.net)
features: Weather

[https://codeberg.org/KL7AF/aprs-tempest](https://codeberg.org/KL7AF/aprs-tempestl)

**Comment by na7q** [comment]
Just an FYI, the contact info text above is incorrectly mine. The link itself is correc. I assume it was a copy and paste, then modify, and he mistakenly left my details in there.

Please correct it to show: kl7af@foghaven.net

**Comment by snopro** [comment]
Corrected the email, original post is accurate now. 

Sorry Mike

**Comment by snopro** [comment]
Didn't mean to close
