### ISSUE TITLE
TOCALL Request: aprs-tempest 

### ISSUE THREAD

**Issue by snopro** [aprsorg/aprs-deviceid#110]
tocall: APTEMP
vendor: KL7AF
model: APRS-Tempest Weather Gateway
class: wx
os: Linux/Unix
contact: [kl7af@foghaven.net](mailto:kl7af@foghaven.net)
features: Weather

[https://codeberg.org/KL7AF/aprs-tempest](https://codeberg.org/KL7AF/aprs-tempestl)

**Comment by hessu** [comment]
Hi,

Thanks, I'm creating the allocation now. The features field is not free text, it's for a few special use cases only (see README.md), so omitting that.
