### ISSUE TITLE
TOCALL ODOT Traffic Alert System: APODOT

### ISSUE THREAD

**Issue by na7q** [aprsorg/aprs-deviceid#112]
tocall: APODOT
vendor: Mike, NA7Q
model: Oregon Department of Transportion Traffic Alerts
class: Service
os: Multiple
contact: [mike.ph4@gmail.com](mailto:mike.ph4@gmail.com)

**Comment by na7q** [comment]
https://aprs.fi/info/a/ODOT

Info for readers.

Provides traffic alerts in the form of objects from the Oregon Department of Transportion. Supports APRS-IS or KISS for sending alerts directly to RF. Uses ODOT API.

**Comment by hessu** [comment]
Hi,

Sorry for the delay. Allocated APODOT for you now!
