### ISSUE TITLE
APRS Messenger TOCALL: APOPYT

### ISSUE THREAD

**Issue by na7q** [aprsorg/aprs-deviceid#116]
tocall: APOPYT
vendor: Mike, NA7Q
model: NA7Q Messenger
class: Software
os: Multiple
contact: [mike.ph4@gmail.com](mailto:mike.ph4@gmail.com)

This is a messaging software.
Built with Python and Tkinter

**Comment by hessu** [comment]
Hi,

Thanks. Sorry for the delay. I have made the allocation now!
