### ISSUE TITLE
ToCall Request: DStarGateway:  APD5T?

### ISSUE THREAD

**Issue by F4FXL** [aprsorg/aprs-deviceid#117]
tocall: APD5T?
vendor: Geoffrey, F4FXL
model: Open Source DStarGateway
class: dstar
os: Multiple
contact: [f4fxl@dstargateway.digital](f4fxl@dstargateway.digital)
features: Advertise DStar Repeaters to APRS-IS, Forwards APRS messages from/to DStar

[https://github.com/F4FXL/DStarGateway](https://github.com/F4FXL/DStarGateway)

Thank You,
Geoffrey F4FXL / KC3FRA

**Comment by F4FXL** [comment]
Hi, any updates on this?

**Comment by hessu** [comment]
Hi!

Sorry for the delay. I've made the allocation now for APD5T?.

**Comment by hessu** [comment]
The features field is for predefined flags, not free text, so I've left it out.

**Comment by F4FXL** [comment]
> The features field is for predefined flags, not free text, so I've left it out.

Thanks for the pull.
Did not know that, what are the flags?

**Comment by hessu** [comment]
The feature flags are listed in README.md, there are just two:
https://github.com/aprsorg/aprs-deviceid/blob/main/README.md#contents
