### ISSUE TITLE
TR80 Aprs Tracker

### ISSUE THREAD

**Issue by ta5lvc** [aprsorg/aprs-deviceid#120]
tocall: APTR80
vendor: TA5LVC
model: TR80 APRS Tracker
class: tracker

**Comment by hessu** [comment]
Hi,

This would overlap with the existing APTR?? allocation. Do you have any other preference of a tocall, please check existing allocations that it isn't there?

**Comment by ta5lvc** [comment]
I made the necessary checks and found that there was no value overlapping with APTR80. Add please

**Comment by ta5lvc** [comment]
tocall: APTLVC
vendor: TA5LVC
model: TR80 APRS Tracker
class: tracker  I made the necessary checks. I would like my preference to be implemented like this, thank you.

**Comment by hessu** [comment]
Hi,

Thanks. I have made the allocation for APTLVC now.
