### ISSUE TITLE
Tocall request : WX LoRa station: APEP??

### ISSUE THREAD

**Issue by tk5ep** [aprsorg/aprs-deviceid#121]
Hi,

tocall: APEP??
vendor: Patrick EGLOFF, TK5EP
model: LoRa WX station
class: wx
os: Embedded
contact: [pegloff@gmail.com]
features: LoRa APRS/APRS-IS WX station
https://github.com/tk5ep
Thanks,

**Comment by hessu** [comment]
Hi,

Thanks, I have made the allocation for APEP?? now.
