### ISSUE TITLE
APZxxx (experimental) is missing.

### ISSUE THREAD

**Issue by wb2osz** [aprsorg/aprs-deviceid#124]
http://aprs.org/aprs11/tocalls.txt includes:

 APZ  APZxxx  Experimental

The APRS protocol specification 1.01, page 14, contains:

The following software version types are reserved (xx and xxx indicate a
version number):
...
...
APZxxx Experimental

Thanks.
John WB2OSZ

**Comment by hessu** [comment]
Thanks,

Added:
```
+ - tocall: "APZ*"
+   vendor: Unknown
+   model: Experimental

```
