### ISSUE TITLE
APRS device by IW1CGW

### ISSUE THREAD

**Issue by iw1cgw** [aprsorg/aprs-deviceid#125]
I would like to request the APLH?? dest call for my projects of APRS: igate, digipeaters, WX stations, telemetry devices.
Currently there are some stations in the world working with my HAM solutions available on GitHub or: https://iw1cgw.wordpress.com/.

To sum up my request

 - tocall: APLHI?
   vendor: Giovanni, IW1CGW
   model: LoRa IGate/Digipeater/Telemetry
   class: digi
   contact: iw1cgw@libero.it	

 - tocall: APLHM?
   vendor: Giovanni, IW1CGW
   model: LoRa Meteostation
   class: wx
   contact: iw1cgw@libero.it

 - tocall: APLHA?
   vendor: Giovanni, IW1CGW
   model:  Meteo
   class: wx
   contact: iw1cgw@libero.it	

 - tocall: APLHB?
   vendor: Giovanni, IW1CGW
   model:  Telemetry
   class: 
   contact: iw1cgw@libero.it

73 and all the best!
Giovanni, IW1CGW

**Comment by hessu** [comment]
Hi,

Just to double check, are the two different "meteo" devices different, or is it an accident?

**Comment by iw1cgw** [comment]
Hi,
yes, they are different devices, I have a class of devices in LoRa and another in old AX25 at 1200 baud. I wanted to distinguish them - if possible -

**Comment by hessu** [comment]
Hi,

Ok. LoRa devices have been recently allocated in the APL* prefix, and people have been using that prefix to filter & display LoRa stations only. So the AX.25 devices should perhaps go to some other prefix

**Comment by iw1cgw** [comment]
You are right ! what I proposed is not good for AX25 devices, can you choose You as an alternative or do I open another ticket just for AX25 devices? - For LoRa I think it could be fine, right?

**Comment by iw1cgw** [comment]
APHR Class for AX25 ? 
-----------------
tocall: APHRM?
vendor: Giovanni, IW1CGW
model: Meteo
class: wx
contact: [iw1cgw@libero.it](mailto:iw1cgw@libero.it)

tocall: APHRT?
vendor: Giovanni, IW1CGW
model: Telemetry
class:
contact: [iw1cgw@libero.it](mailto:iw1cgw@libero.it)

**Comment by hessu** [comment]
Hi,

Ok, thanks. I have allocated APLHI? APLHM? APHRM? APHRT? in ad79d6838062cbd6001f6e63c9fec719929c0247 .

**Comment by iw1cgw** [comment]
thanks for your patience ! -- 73 iw1cgw Giovanni @ North West Italy
