### ISSUE TITLE
APRS app/daemon for WX and Telemetry

### ISSUE THREAD

**Issue by SP9MLI** [aprsorg/aprs-deviceid#126]
I kindly ask You to add tocall "APEMLx" for my WX and telemetry projects. 
Currently, daemon works on windows/linux.

 - tocall: APEML?
 - vendor: Leszek, SP9MLI
 - model: SP9MLI for WX, Telemetry
 - class: daemon
 - os: multiple
 - contact: sp9mli@gmail.com
 
 Thank You for Your work, 73!
SP9MLI

**Comment by hessu** [comment]
Hi,

Thanks, I have made the allocation. I used class: software as it has been used for other daemons so far (aprsd, aprx, etc).

**Comment by SP9MLI** [comment]
Thank You 🙃

pt., 9 lut 2024, 17:57 użytkownik Heikki Hannikainen <
***@***.***> napisał:
