### ISSUE TITLE
APRS Service: ioreth/APRSPH

### ISSUE THREAD

**Issue by jangelor** [aprsorg/aprs-deviceid#127]
tocall: APZIOR
vendor: J. Angelo Racoma DU2XXR/N2RAC
model: APRSPH net bot based on Ioreth
class: service
os: linux
contact: info@aprsph.net
features: messaging

**Comment by hessu** [comment]
Hi,

The APZ* prefix has traditionally been for experimental use, not for persistent, registered allocations (yes, there are some old exceptions there of already-deployed devices). I have now allocated **APAIOR** for you instead, I hope that's OK. Please comment if you'd like something else.

**Comment by jangelor** [comment]
Thank you, Hessu. That should be fine.
