### ISSUE TITLE
APESPG and APESPW gone missing

### ISSUE THREAD

**Issue by oh2th** [aprsorg/aprs-deviceid#144]
Allocated since May 2020 by me from late Bob.

APESPG = ESP SmartBeacon APRS-IS Client
APESPW = ESP Weather Station APRS-IS Client

Can be seen in original [tocalls.txt](http://www.aprs.org/aprs11/tocalls.txt)

**Comment by hessu** [comment]
Oops, sorry. I seem to have missed a few of Bob's updates back then, 
APGDTx APGDTx APOSBx are missing too.

Unfortunately I have also allocated the APESP? prefix for LY3PH APRS-ESP in commit df785944496924f389b57a5cbd40076a283396f7 in response to request #66 so there's now a bit of an overlap present.

Do you have a lot of these running, would it be difficult to update them to a different tocall? Sorry for this mixup.

**Comment by hessu** [comment]
Fixed!
