### ISSUE TITLE
Lora Aprs i-Gate

### ISSUE THREAD

**Issue by ta5lvc** [aprsorg/aprs-deviceid#145]
tocall: APTIF
vendor: TA5Y
model: TIF LORA APRS I-GATE
class: i-gate

**Comment by hessu** [comment]
Hi,

Recently all allocations for LoRA devices have been made in the APL* prefix. Would you be alright with the allocation of APLIFT?

APLTIF is within another existing allocation already.

**Comment by ta5lvc** [comment]
It can be APZTIF, APTIF or APYTIF. If there is no allocation regarding
these. Thanks

Heikki Hannikainen ***@***.***>, 5 Nis 2024 Cum, 22:24
tarihinde şunu yazdı:

**Comment by hessu** [comment]
Hi,

As I mentioned before: All recent LoRa allocations have been with an **APL** prefix, so I'd prefer to allocate you a tocall which starts with APL, too. APLTIF is already taken, so I'll allocate you the prefix APLIF? where you can use the last wildcard letter/number for variants.

I hope this is alright.

**Comment by ta5lvc** [comment]
Ok.

Heikki Hannikainen ***@***.***>, 30 Nis 2024 Sal, 00:53
tarihinde şunu yazdı:
