### ISSUE TITLE
N1AF LoRa I-gate and tracker

### ISSUE THREAD

**Issue by n1af-ham** [aprsorg/aprs-deviceid#147]
Greetings!  I'm interested in registering 3 LoRa-APRS tocall's:

 - tocall: APLZX?
   vendor: N1AF
   model: LoRa-APRS Tracker
   class: tracker
   os: embedded
   contact: lora-aprs@n1af.org

 - tocall: APLZY?
   vendor: N1AF
   model: LoRa-APRS Digipeater
   class: digi
   os: embedded
   contact: lora-aprs@n1af.org

 - tocall: APLZZ?
   vendor: N1AF
   model: LoRa-APRS iGate
   class: igate
   os: embedded
   contact: lora-aprs@n1af.org
   
I'm flexible on the actually assigned tocall's, just included some possible 5-char prefixes below APL* that aren't allocated to anything yet.

**Comment by hessu** [comment]
Hi,

Just to confirm: Are these actual different devices and different software, or just one software switching between igate / digipeater / tracker mode?

**Comment by n1af-ham** [comment]
Hi Hessu,

All 3 are different independent software projects.

-Ryan (N1AF)

**Comment by hessu** [comment]
Hi,

For some reason all of the LoRa allocation requests have recently requested 3 to 5 tocalls. This will increase the size of the database and require more maintenance work, so I'm allocating a single prefix for each applicant for now. The last letter can be used by the author to identify variants. I hope this is OK.

```
 - tocall: APLZX?
   vendor: N1AF
   model: LoRa-APRS
   os: embedded
   contact: lora-aprs@n1af.org
```
