### ISSUE TITLE
BD5HTY LoRa I-gate wx and tracker

### ISSUE THREAD

**Issue by BD5HTY** [aprsorg/aprs-deviceid#150]
Greetings! I'm interested in registering 4 LoRa-APRS tocall's:
- tocall: APHZA?
   vendor: Huang Xuewu, BD5HTY
   model: LoRa iGate
   class: igate
   os: embedded
   contact: bd5hty@gmail.com

 - tocall: APHZB?
   vendor: Huang Xuewu, BD5HTY
   model: LoRa Tracker
   class: tracker
   os: embedded
   contact: bd5hty@gmail.com
   
- tocall: APHZC?
   vendor: Huang Xuewu, BD5HTY
   model: 4G Tracker
   class: tracker
   os: embedded
   contact: bd5hty@gmail.com

   
- tocall: APHZD?
   vendor: Huang Xuewu, BD5HTY
   model: LoRa APRS Weather Station
   class: wx
   os: embedded
   contact: bd5hty@gmail.com

73!!

**Comment by hessu** [comment]
Hi,

For some reason all of the LoRa allocation requests have recently requested 3 to 5 tocalls. This will increase the size of the database and require more maintenance work, so I'm allocating a single prefix for each applicant for now. The last letter can be used by the author to identify variants. I hope this is OK.

```
 - tocall: APLZA?
   vendor: Huang Xuewu, BD5HTY
   model: LoRa
   os: embedded
   contact: bd5hty@gmail.com

 - tocall: APHZC?
   vendor: Huang Xuewu, BD5HTY
   model: 4G Tracker
   class: tracker
   os: embedded
   contact: bd5hty@gmail.com

```
