### ISSUE TITLE
LoRa devices for XE3JAC

### ISSUE THREAD

**Issue by XE3JAC** [aprsorg/aprs-deviceid#151]
Hello, could you help me register these parameters?

-Device 1
   tocall: PSKAPS
   vendor: Jose, XE3JAC
   model: ESP-32 LoRa iGate
   class: igate
   os: Embedded
   contact: xe3jac@gmail.com

-Device 2
   tocall: PSKAPT
   vendor: Jose, XE3JAC
   model: ESP-32 LoRa Tracker
   class: tracker
   os: Embedded
   contact: xe3jac@gmail.com

-Device 3 
   tocall: PSKAPV
   vendor: Jose, XE3JAC
   model: ESP-32 LoRa WX 
   class: wx
   os: Embedded
   contact: xe3jac@gmail.com

-Device 4
   tocall: PSKAPW
   vendor: Jose, XE3JAC
   model: ESP-32 LoRa Digipeater
   class: digi
   os: Embedded
   contact: xe3jac@gmail.com

-Device 5
   tocall: PSKAPX
   vendor: Jose, XE3JAC
   model: ESP-32 LoRa 4G Tracker
   class: tracker
   os: Embedded
   contact: xe3jac@gmail.com

There are 5 different software versions, for different boards.

**Comment by hessu** [comment]
Hi,

For some reason all of the LoRa allocation requests have recently requested 3 to 5 tocalls. I understand these are forks of existing software, from a single distribution which is built for multiple boards or purposes. This will increase the size of the database and require more maintenance work, so I'm allocating a single prefix for each applicant for now. The last letter can be used by the author to identify variants. I hope this is OK.

```
 - tocall: APLPS?
   vendor: Jose, XE3JAC
   model: ESP-32 LoRa
   os: embedded
   contact: xe3jac@gmail.com
```
