### ISSUE TITLE
Add openSPOT4

### ISSUE THREAD

**Issue by nonoo** [aprsorg/aprs-deviceid#161]
Please add the openSPOT4 to tocall.yaml:

- tocall: APOSE?
  vendor: SharkRF
  model: openSPOT4
  class: gadget
  os: Embedded
  contact: [info@sharkrf.com](mailto:info@sharkrf.com)

**Comment by hessu** [comment]
Hi,

Looking at the previous use of APOSB? and APOSW? allocations, I see that the wildcard has not been utilised at all. How about using APOSB4 for openSPOT4 and marking it as such in the database? Feels weird allocating complete new prefixes for new versions but not using the wildcard (?) for anything.

**Comment by nonoo** [comment]
Yes, we don't use wildcards, those can be omitted. OSW is our product code for the openSPOT2, OSB is for the openSPOT3 and OSE is the openSPOT4. We can release a firmware update for the OS4 to use a different APRS device ID in case APOSE can't be added.

**Comment by hessu** [comment]
Seems like quite a lot of APOSE devices are out there in the field already. Do you have automatic firmware updates, do you get a large percentage of devices updated in the end?

**Comment by nonoo** [comment]
Yes, automatic upgrade is available, most users let their OS4s update.

**Comment by hessu** [comment]
Excellent. How about if I adjust it like this:

```
# prefix of APOSB? for SharkRF (future devices can be added by varying the last character)
 - tocall: APOSB?
   vendor: SharkRF
   contact: info@sharkrf.com

# specific allocations for openSPOT3 and openSPOT4
 - tocall: APOSB
   vendor: SharkRF
   model: openSPOT3
   class: gadget
   os: embedded
   contact: info@sharkrf.com

 - tocall: APOSB4
   vendor: SharkRF
   model: openSPOT4
   class: gadget
   os: embedded
   contact: info@sharkrf.com
```

openSPOT5 can be APOSB5, and so on, in the future.

**Comment by nonoo** [comment]
Can we use APSRF? for SharkRF devices?
APOSB4 for the OS4 is fine.

**Comment by hessu** [comment]
Unfortunately there is another existing allocation for `APSRF?` already.

**Comment by nonoo** [comment]
Ok, APOSB? will be fine.
