### ISSUE TITLE
Fix openSPOT2 and openSPOT3 information

### ISSUE THREAD

**Issue by nonoo** [aprsorg/aprs-deviceid#162]
Please fix the openSPOT2 and openSPOT3 information:

- tocall: APOSW?
  vendor: SharkRF
  model: openSPOT2
  class: gadget
  os: Embedded
  contact: [info@sharkrf.com](mailto:info@sharkrf.com)

- tocall: APOSB?
  vendor: SharkRF
  model: openSPOT3
  class: gadget
  os: Embedded
  contact: [info@sharkrf.com](mailto:info@sharkrf.com)

**Comment by hessu** [comment]
Thanks, pushing the update now! Sorry for the delay.
