### ISSUE TITLE
Add tesla-aprs

### ISSUE THREAD

**Issue by nonoo** [aprsorg/aprs-deviceid#163]
I'm developing an app called [tesla-aprs](https://github.com/nonoo/tesla-aprs) which lets Tesla vehicle owners to transmit vehicle positions and data to APRS-IS. Please add the identifier to tocall.yaml.

- tocall: APTSLA
  vendor: HA2NON
  model: tesla-aprs
  class: daemon
  os: Multiple
  contact: [nonoo@nonoo.hu](mailto:nonoo@nonoo.hu)

**Comment by hessu** [comment]
Thanks, making the allocation now! Sorry for the delay.
