### ISSUE TITLE
new TOCALL Request: LoRa APRS Balloon software

### ISSUE THREAD

**Issue by SQ2CPA** [aprsorg/aprs-deviceid#165]
Hello!

I would want to request the TOCALL "APLSKY" for my LoRa APRS balloon software. 

```
tocall: APLSKY
vendor: Damian, SQ2CPA
model: ESP32 LoRa Balloon
class: tracker
os: embedded
contact: sq2cpa@gmail.com

```

That's my first own device ID request so I hope everything is correct :)

Thanks, 73!
Damian SQ2CPA

**Comment by hessu** [comment]
Hi,

Unfortunately that would overlap with an existing allocation of 'APLS*' (which is admittedly unnecessarily large, only APLS01 has been used lately, but it is what it is).

How about APLDKY ?

**Comment by SQ2CPA** [comment]
Ok, sorry I missed that. 

Please use `APLFLY`, I checked it with '*' and this seems to be free.

**Comment by hessu** [comment]
Ok, thanks! Registering as APLFLY.
