### ISSUE TITLE
9M2PJU APRS BOT

### ISSUE THREAD

**Issue by 9M2PJU** [aprsorg/aprs-deviceid#166]
I'm running APRS Bot

tocall: APRPJU
vendor: Piju 9M2PJU
model: 9M2PJU Bot
class: daemon
os: Multiple
contact: 9m2pju@hamradio.my
features:
      - messaging

**Comment by 9M2PJU** [comment]
What incoming ports do I need to open ?

**Comment by hessu** [comment]
Thanks, I'm making the allocation now.

**Comment by 9M2PJU** [comment]
Thanks, but please change the model name from 9M2PJUT Bot to 9M2PJU APRS Bot to honor WB4APR APRS.
