### ISSUE TITLE
Arduino APRS Tracker

### ISSUE THREAD

**Issue by mzakiab** [aprsorg/aprs-deviceid#167]
i'm create an Arduino APRS tracker as my experimental.

tocall: APZKEY
vendor: 9W2KEY
model: Arduino APRS
class: tracker 
os: Linux
contact: mzakiab@gmail.com
features:
- tracking
- igate

**Comment by hessu** [comment]
Hi,

Experimental use in the APZ* prefix is not added to the database. It is intended to be use for temporary experiments and development of unreleased software; if you are to release the software or device it can be added outside the APZ prefix.

Thanks for interest!
