### ISSUE TITLE
ATMega328P APRS

### ISSUE THREAD

**Issue by mzakiab** [aprsorg/aprs-deviceid#170]
i'm create an ATMega328P APRS tracker.

```
tocall: APKEYn
vendor: 9W2KEY
model: ATMega328P APRS
class: tracker
os: Linux/Unix
contact: mzakiab@gmail.com
features:
        - tracking
```

**Comment by hessu** [comment]
Hi,

Registering as requested. The ATMega328P probably does not run Linux (fast enough) so I've marked it with os: embedded instead, and removed the "tracking" feature; the only feature flag needed or supported is "messaging". It's there for technical purposes, not for the purpose of listing all possible features.

```
 - tocall: APKEYn
   vendor: 9W2KEY
   model: ATMega328P APRS
   class: tracker
   os: embedded
   contact: mzakiab@gmail.com

```
