### ISSUE TITLE
Modify Tocall for APRRF? deviceId

### ISSUE THREAD

**Issue by f1evm** [aprsorg/aprs-deviceid#174]
Hello,

I had registered this deviceId :

- tocall: APRRF?
   vendor: Jean-Francois Huet F1EVM
   model: Tracker for RRF
   class: tracker
   os: embedded
   contact: f1evm@f1evm.fr
   features:
     - messaging

Could you, please, modify the vendor name  to "RRF - Réseau des Répéteurs Francophones ".
Other informations left unchanged.

Many Thanks.

73s
Jean-Francois Huet
F1EVM

**Comment by hessu** [comment]
Thanks for the update! Adjusted vendor name as requested.

**Comment by f1evm** [comment]
Many Thanks !



Le 9 octobre 2024 à 19:27:01 +02:00, Heikki Hannikainen ***@***.***> a écrit :
