### ISSUE TITLE
request new APRS device id

### ISSUE THREAD

**Issue by hb9pae** [aprsorg/aprs-deviceid#176]
Dr OM
I'm interested in registering a new APRS divice-id:

tocall: AHB9AK
vendor: SWISS-ARTG
model: LoRa iGate RPI
class: Network
os: Linux/Unix
contact: hb9pae@gmail.com

73 de peter, hb9pae
hb9pae@swiss-artg.ch

**Comment by hessu** [comment]
Hi,

Do you have a link to your LoRa firmware branch?

**Comment by hb9pae** [comment]
Hi Heikki

yes here it is: 
 
Project discription https://www.swiss-artg.ch/index.php?id=174
Download Sources https://cloud.hoststar.ch/s/GytsTsQSYSoyAXk


Thank you 

73 de peter, hb9pae

**Comment by hessu** [comment]
Hi,

Sorry for my slow reply.

The APRS spec (section 4) indicates all software identifiers start with "AP", and the LoRa devices have been going to the APL prefix lately, so I've allocated **APLHB9** for you, as follows. I hope that's ok.

```
 - tocall: APLHB9
   vendor: SWISS-ARTG
   model: LoRa iGate RPI
   class: igate
   os: Linux/Unix
   contact: hb9pae@gmail.com
```

73!
