### ISSUE TITLE
APATAR and APIZCI update request

### ISSUE THREAD

**Issue by barisdinc** [aprsorg/aprs-deviceid#177]
Hello,
One of our developer's call signed changed. Is it possible to do an update on database **vendor** fields as follows:

both for **APATAR** and **APIZCI**

TA7W/OH2UDS Baris Dinc and TA6AD Emre Keles

Thanks
Baris
TA7W/OH2UDS

**Comment by hessu** [comment]
Hi,

Thanks for the update, adjusting the vendor name.
