### ISSUE TITLE
Request new APRS  device id

### ISSUE THREAD

**Issue by sm0svx** [aprsorg/aprs-deviceid#178]
Hi,

I with to register a new device id for my application SvxLink. I suggest the following information.

tocall: APSVXn
vendor: Tobias Blomberg, SM0SVX
model: SvxLink
class: daemon
os: Linux/Unix
contact: aprs-deviceid@cyberspejs.net

73's de SM0SVX / Tobias

**Comment by hessu** [comment]
Hi!

Thanks, and sorry for the slow reply. Allocated **APSVX?** - as requested, but the wildcard will accept any number or letter.

73!
