### ISSUE TITLE
register system/device identifier

### ISSUE THREAD

**Issue by oe5hpm** [aprsorg/aprs-deviceid#180]
Hi,

I with to register a new device id for application dxlAPRS.

tocall: APNLnn
vendor: oe5dxl, oe5hpm
model: aprs digipeater, aprs i-gate
class: daemon
os: Linux/Unix

73's de oe5hpm, hannes

**Comment by hessu** [comment]
Hi,

Sorry for the slow reply. Thanks for the request. Allocated now as follows - made the wildcard (??) accept two alphanumeric characters, and placed **dxlAPRS** as the model. I hope that's alright.

```
 - tocall: APNL??
   vendor: OE5DXL, OE5HPM
   model: dxlAPRS
   class: daemon
   os: Linux/Unix
```
