### ISSUE TITLE
Request for new lora device id allocation

### ISSUE THREAD

**Issue by piotr022** [aprsorg/aprs-deviceid#63]
Hi,
Hello im going to finish my LoRa/FSK/AFSK APRS digi and tracker projects soon.
Can i ask you to add propsed devices ids to tocalls list? 
My proposition: APLP??

- tocall: APLP0?
   vendor: SQ9P
   model: fajne digi
   class: digi
   os: Embedded
   contact: sq9p.peter@gmail.com
   features:
      - digipeating
      - crossdigi
      - low-power
      - basic-weater-reports
  
- tocall: APLP1?
   vendor: SQ9P
   model: LORA/FSK/AFSK fajny tracker
   class: tracker
   os: Embedded
   contact: sq9p.peter@gmail.com

**Comment by hessu** [comment]
Thanks, and sorry for the delay.

This is implemented in PR 65, commit 525b38617490ee6b392b7856d86ca092e341397a.
