### ISSUE TITLE
New APRS Device ID for LY3PH APRS-ESP

### ISSUE THREAD

**Issue by erstec** [aprsorg/aprs-deviceid#66]
Please add new TOCALL for my new embedded APRS Tracker / IGate / Digi Open Source Project - APRS-ESP
 - tocall: APES??
   vendor: LY3PH
   os: embedded

It's in hw/fw testing / pre-release stage now.
Last '??' digits will be used for versioning/hardware/features separation

73, LY3PH / Ernest

**Comment by erstec** [comment]
Project assembled, tested and released, still with experimental destination.

**Comment by hessu** [comment]
Hi,

Sorry for the very long delay. I have assigned you with APESP?, I hope that's alright. We only have 676 4-letter prefixes in the AP?? space available, with 5-letter prefixes there's more space to grow.

**Comment by erstec** [comment]
> Hi,
> 
> Sorry for the very long delay. I have assigned you with APESP?, I hope that's alright. We only have 676 4-letter prefixes in the AP?? space available, with 5-letter prefixes there's more space to grow.

Thank you!
Due to mentioned limitations APESP? is ok of course!

73!

**Comment by oh2th** [comment]
In May 2020 these two were allocated as:
APESPG = ESP SmartBeacon APRS-IS Client
APESPW = ESP Weather Station APRS-IS Client

Could these be restored as they were?

**Comment by hessu** [comment]
Hi,

Unfortunately I have missed the APESPG and APESPW allocations to OH2TH by Bob in 2020, and then subsequently made an overlapping allocation. This needs to be resolved by reallocating.

Here's the number of stations seen in 2024 (according to my database on aprs.fi) using different `APESP?` tocalls:
```
APESPW   2
APESPG   45
APESP1   2
```

Do you have any visibility if these are running the software from @oh2th or from @erstec ?  Have you released code using these tocalls?

**Comment by erstec** [comment]
@hessu 
APESP1 is what mine project using, FW is deployed and running on several (at least I know) nodes.
We can split interval, like APESPx, where x is digit are more than enough for me.

**Comment by hessu** [comment]
If you're currently using APESP1 only, the simple approach would be to make an allocation of APESP1 to you to resolve the overlap. Would that be alright for you?

**Comment by erstec** [comment]
Yes, it's ok, Thank you

**Comment by oh2th** [comment]
Sounds like aplan

**Comment by hessu** [comment]
Hi,

I have fixed the allocations as agreed above.
