### ISSUE TITLE
New APRS ID Request: W9JAJ ATTiny

### ISSUE THREAD

**Issue by jamez70** [aprsorg/aprs-deviceid#67]
### APRS ID Request
Please add new TOCALL for my new embedded **APRS Tracker - ATTiny** APRS Tracker Project

tocall: `APTKxx`
vendor: `W9JAJ`
os: none / embedded loop
Currently in development with working prototypes
Last 2 digits `'xx'` will be used for versioning and different revisions
73, `W9JAJ` - Jim, Kenosha, WI

**Comment by hessu** [comment]
Hi,

Sorry for the terribly long delay.

I've allocated you with APTKJ? - I hope that's alright. There's only 676 4-letter prefixes in the AP?? space available so I'm mostly allocationg 5-letter prefixes now - if different models need to be identified, those can be added with additional 5-letter prefixes later on.

```
+ - tocall: APTKJ?
+   vendor: W9JAJ
+   model: ATTiny APRS Tracker
+   os: embedded

```
