### ISSUE TITLE
NEW APRS device ID request: RadCommSoft PicoAPRSTracker

### ISSUE THREAD

**Issue by guitarpicva** [aprsorg/aprs-deviceid#68]
Pico APRS Tracker project at https://github.com/guitarpicva/PicoAPRSTracker

 - tocall: APPCOx
   vendor: RadCommSoft, LLC
   model: PicoAPRSTracker v.x
   class: tracker
   os: embedded
   contact: ab4mw@radcommsoft.com

**Comment by hessu** [comment]
Hi,

Sorry for the terribly long delay.

I have added the assignment as requested with a slight formatting fix:

`+ - tocall: APPCOx
+   vendor: RadCommSoft, LLC
+   model: PicoAPRSTracker
+   class: tracker
+   os: embedded
+   contact: ab4mw@radcommsoft.com
`

**Comment by guitarpicva** [comment]
The "x" was meant to leave room for version ID's
