### ISSUE TITLE
New APRS Device Id Request: F1EVM Tracker for RRF

### ISSUE THREAD

**Issue by f1evm** [aprsorg/aprs-deviceid#70]
Could you add this "To Call" for RRF Network ( SvxLink based french FM repeater network).
This will add tracker and messaging for the RRF hotspots.
Thanks. 73s. F1EVM.

- tocall: APRRFx
   vendor: Jean-Francois Huet F1EVM
   model: Tracker for RRF
   class: tracker
   os: embedded
   contact: f1evm@f1evm.fr
   features:
      - messaging

Nota : the last digit is for model identification.

**Comment by hessu** [comment]
Hi,

Thank you for the allocation request, and sorry for the slow processing. I have made this allocation now as requested.

**Comment by f1evm** [comment]
Hi,

It's fine.
Thank you very much.

73s
Jean-Francois F1EVM
