### ISSUE TITLE
New APRS Device ID request: HP3ICC Raspbian Proyect

### ISSUE THREAD

**Issue by hp3icc** [aprsorg/aprs-deviceid#73]
thank you add new tocall id to identify Raspbian Project by HP3ICC, Esteban Mackay , mail: setcom40@gmail.com 
73.

 - tocall: APHP??
   vendor: HP3ICC
   model: Raspbian Proyect by HP3ICC

**Comment by hessu** [comment]
Hi,

Thank you for the request, and sorry for the slow processing.

I have allocated you with APHPI? as there are only 676 4-letter prefixes available in the AP?? prefix space. Additional 5-letter prefixes can be allocated for more specific models if necessary.

I have also used the spelling "Raspbian Project" as that was also used in the ticket comment text, and is correct English. Please reopen ticket if you would like to have "Raspbian Proyect" as the name, it's easy to change if necessary.

**Comment by hp3icc** [comment]
Very well, I was unaware of the 4-digit limitations, and I understand it, to avoid language corrections, I will give you the following query, is it possible to replace APHPI? , and assign APHPIB , for : Python APRS Beacon by HP3ICC , and APHPIW , for : Python APRS WX by HP3ICC , if it is positive, inform me to change the tocall in the code of both projects , if it is not possible , then I stay with APHPI ? , and we only replace : Raspbian Project , by : Python APRS by HP3ICC , I share the links and I await your response , very grateful for your invested time to help me

Regards 

https://gitlab.com/hp3icc/python-aprs-beacon

https://gitlab.com/hp3icc/python-aprs-wx

Enviado desde mi iPhone

**Comment by hessu** [comment]
Hi,

Ok, I have reallocated as following:

```
 - tocall: APHPIB
   vendor: HP3ICC
   model: Python APRS Beacon

 - tocall: APHPIW
   vendor: HP3ICC
   model: Python APRS WX
```

**Comment by hessu** [comment]
For new additions, please open a new ticket. Thanks.
