### ISSUE TITLE
New APRS TOCALL Request: CD2RXU ESP32 LoRa Station

### ISSUE THREAD

**Issue by richonguzman** [aprsorg/aprs-deviceid#74]
I would like to add to the TOCALL list the following:

- tocall: APLR0X (with X from 1 to 9, where "LR" = LoRa Station + R letter of identification)
   vendor: Ricardo (CD2RXU)
   model: ESP32 LoRa Station
   class: Tracker/TNC with message and Winlink capability
   os: embedded
   contact: richonguzman@gmail.com

**Comment by hessu** [comment]
Hi,

Thank you for the request, and sorry for the slow processing. I have made the allocation as follows. The class field is not a free-text field, it's a keyword pointing to one of the predefined classes, so I picked the "tracker" class. Please reopen ticket and request adjustment if necessary.

```
 - tocall: APLR0?
   vendor: Ricardo, CD2RXU
   model: ESP32 LoRa Station
   class: tracker
   os: embedded
   contact: richonguzman@gmail.com
```
