### ISSUE TITLE
TOCALL request for satellites from India: BeliefSat APOVU?

### ISSUE THREAD

**Issue by rnbokade** [aprsorg/aprs-deviceid#75]
Can you please allocate APOVUx for series of APRS satellites from India.
We are building BeliefSat-1 with UHF APRS digipeater, so we would like to have APOVU1 for it

**Comment by hessu** [comment]
Hi,

Thank you for the request. As the single-character wildcard can be used to specify future variants, I removed the -1 prefix from the model string. I googled up the name of the organisation for the vendor string, I hope that's alright. Please reopen the ticket if it is necessary to adjust the allocation somehow.

```
+ - tocall: APOVU?
+   vendor: K J Somaiya Institute
+   model: BeliefSat
```
