### ISSUE TITLE
new device id APHPIA by HP3ICC

### ISSUE THREAD

**Issue by hp3icc** [aprsorg/aprs-deviceid#83]
hi team please add APHPIA call, i will use this call for all digi, igate and tracker projects i develop mounted on arduino modules. Esteban Mackay setcom40@gmail.com.
73.

- tocall: APHPIA
   vendor: HP3ICC
   model: Arduino APRS

**Comment by hessu** [comment]
Hi,

The allocation of APHPIA is done.

**Comment by hp3icc** [comment]
hello heikiki, query, how often, aprs.fi, update the tocall list, he observed the APHPIA tocall in the list, but aprs.fi seems to have not yet updated the new list, I imagine it must take some time

73.

Enviado desde mi iPhone
