### ISSUE TITLE
New identifier: Codec2Talkie

### ISSUE THREAD

**Issue by sh123** [aprsorg/aprs-deviceid#84]
Hi, have request to add application to official list https://github.com/sh123/codec2_talkie/issues/53

tocall: APCTLK
vendor: Open Source
model: Codec2Talkie
class: software

**Comment by ldeffenb** [comment]
Is this client APRS message capable?

**Comment by sh123** [comment]
It supposed to be, but I did not test it extensively, ack-ing might not be implemented.

**Comment by hessu** [comment]
Hi,

The allocation for APCTLK is done. I figured it's an Android app so I adjusted the class to be "app", please let me know if I got that wrong.
