### ISSUE TITLE
Python library

### ISSUE THREAD

**Issue by xssfox** [aprsorg/aprs-deviceid#87]
I've made a quick Python library for looking up tocalls. It doesn't cover things like MIC-E but it might still be useful for others. 

Might be worth adding to the home page to save others some time implementing their own.

https://github.com/xssfox/aprs_tocall / https://pypi.org/project/aprs-tocall/

**Comment by hessu** [comment]
Thanks, I'll add a link.

Took a quick look, seems like it does a linear scan against all entries in the allocation table, which is a bit slow. The perl module loads all non-wildcard entries in a hash/dict and tries a lookup from there first. The wildcard-contained entries are loaded in another dictionary of lists, keyed by the constant prefix part of the wildcard-containing entry. The lookup can then find the regexps by a couple of hash lookups:

https://github.com/hessu/perl-aprs-deviceid/blob/master/DeviceID.pm#L397
