### ISSUE TITLE
New APRS TOCALL Request: SoftRF Ham Edition

### ISSUE THREAD

**Issue by lyusupov** [aprsorg/aprs-deviceid#97]
Hello Heikki !

We've completed development of an [APRS tracker](https://github.com/lyusupov/SoftRF/wiki/Ham-Edition) and would like to ask your assistance to add the TOCALL in the list.

Could you, please, allocate the following record:

```
 - tocall: APSRF?
   vendor: SoftRF
   model: Ham Edition
   class: tracker
   os: embedded
```

   Thank you !
   Linar.

**Comment by hessu** [comment]
Thanks, I'm creating this allocation now.

Noted that the wiki page recommends two broken igates which corrupt packets. Please do not recommend multimon-ng based igates, as they cause problems to the network. Thanks!
