### ISSUE TITLE
LoRa APRS Meteo by OK2DDS

### ISSUE THREAD

**Issue by ddaqua6** [aprsorg/aprs-deviceid#98]
Hello,

I would like to request allocation of ALGMx dest call to my project of [LoRa_APRS_Meteo](https://github.com/ddaqua6/LoRa_APRS_Meteo), which is a combination of LoRa igate, digipeater and WX station. There are currently some stations in the world working with this firmware, which uses this prefix.

To sum up my request

- tocall: APLGM?
- vendor: David, OK2DDS
- model: LoRa APRS Meteo
- contact: david@ok2dds.cz

73 and all the best!
David, OK2DDS

**Comment by hessu** [comment]
Hi,

APLG?? is already allocated to OE5BPA, so APLGM? cannot be allocated for you, as it would overlap a recently created allocation.

How about `tocall: APLDD?` instead?

**Comment by ddaqua6** [comment]
Hello,

then we could change it so we can better distinguish between the two parts of the device. As I mentioned, it's an WX station combined with igate/digipeater. So let's alocate APLDM? to "LoRa Meteostation" (WX) and APLDI? to "LoRa IGate/Digipeater" (digi)

**Comment by hessu** [comment]
Hi,

Ok, I'm allocating APLDM? and APLDI? .
